baseURL = 'http://www.STKalinow.ca/'
languageCode = 'en-us'
title = 'STKalinow'
theme = 'papermod'

[params.homeInfoParams]
Title = "Welcome to STKalinow"
Content = "I am Stas Kalinowski. This is a website to track my learnings, share my thoughts, and improve my writing. I am currently focused on writing, improving my spaced repetition practice, and learning about agents + robotics."

[[params.socialIcons]]
name = "Github"
url = "https://github.com/STKalinowski"

[[params.socialIcons]]
name = "Twitter"
url = "https://twitter.com/STKalinow"

[outputs]
home = ["HTML", "RSS", "JSON"] # is necessary

[[menu.main]]
name = 'Archive'
identifier = 'Archive'
url = '/archives'

[[menu.main]]
name = 'Search'
identifier = 'search'
url = '/search'