baseURL = 'www.STKalinowski.ca/'
languageCode = 'en-us'
title = 'STKalinow'
theme = 'papermod'

[params.homeInfoParams]
Title = "Welcome"
Content = "I am Stas Kalinowski. Using this site to share my thoughts and practice my writing. I am currently focused on writing, my memory practice, and studying ML."

[[params.socialIcons]]
name = "Github"
url = "https://github.com/STKalinowski"

[[params.socialIcons]]
name = "Twitter"
url = "https://twitter.com/STKalinow"

[outputs]
home = ["HTML", "RSS", "JSON"] # is necessary

[[menu.main]]
name = 'Archive'
identifier = 'Archive'
url = '/archives'

[[menu.main]]
name = 'Search'
identifier = 'search'
url = '/search'